/**
 * Portable website behaviour contract.
 *
 * Components intentionally describe artist-authored intent rather than an
 * engine implementation.  A Three/Rapier/site adapter may consume a record,
 * but a missing adapter must never make the authored record disappear.
 */

export const PORTABLE_COMPONENT_SCHEMA_VERSION = 1 as const

export type JsonPrimitive = string | number | boolean | null
export type JsonValue = JsonPrimitive | readonly JsonValue[] | { readonly [key: string]: JsonValue }
export type JsonObject = { readonly [key: string]: JsonValue }

/** Object IDs are Blendlink's rename-stable IDs; objectName is only a useful
 * artist-facing diagnostic when a manifest is inspected outside Blender. */
export type PortableComponentTarget =
  | { kind: 'scene' }
  | { kind: 'object'; objectId: string; objectName?: string }

export const SCENE_COMPONENT_TARGET: PortableComponentTarget = { kind: 'scene' }

export interface PortableComponentRecord {
  /** Stable authoring ID. Duplicating an object must create a new component ID. */
  id: string
  /** Namespaced runtime contract, e.g. blendlink.bloom or studio.ripple. */
  type: string
  schemaVersion: typeof PORTABLE_COMPONENT_SCHEMA_VERSION
  enabled: boolean
  target: PortableComponentTarget
  /** Plain JSON only: portable across Blender, glTF, manifests, and adapters. */
  values: JsonObject
}

/** Keep the runtime descriptor additive without making the generic runtime
 * install a component engine. Consumers that import the public component
 * contract see the same descriptor field generated by typegen. */
declare module './runtime.js' {
  interface CompiledSceneDescriptor {
    components?: readonly Readonly<PortableComponentRecord>[] | null
  }
}

export type ComponentTargetKind = PortableComponentTarget['kind']
export type ComponentPortability = 'core' | 'adapter'
export type ComponentLifecyclePhase =
  | 'initial' | 'update' | 'fixed' | 'post-depth' | 'post-hdr' | 'post-ldr'
export type ComponentCardinality = 'one-per-target' | 'many-per-target' | 'one-per-scene'
export type ComponentRuntimeCost = 'free' | 'low' | 'medium' | 'high' | 'very-high'
export type ComponentAdapterKind = 'webgl' | 'tsl'
export type ComponentAdapterSupportLevel = 'production' | 'preview' | 'fallback' | 'unavailable'
export type ComponentRuntimeCapability =
  | 'post-pipeline' | 'hdr-color' | 'depth' | 'normals' | 'velocity'
  | 'camera' | 'raycast' | 'pointer' | 'dom-accessibility'
  | 'animation' | 'audio' | 'physics' | 'scroll-source'

export interface ComponentAdapterSupport {
  webgl: ComponentAdapterSupportLevel
  tsl: ComponentAdapterSupportLevel
}

export interface ComponentFieldMetadata {
  label: string
  description: string
  kind: 'boolean' | 'number' | 'string' | 'color' | 'object-reference' | 'enum'
  default: JsonValue
  min?: number
  max?: number
  options?: readonly string[]
  required?: boolean
}

export interface PortableComponentDefinition {
  id: string
  label: string
  description: string
  category: 'Presentation' | 'Rendering' | 'Interaction' | 'Animation' | 'Audio'
  targets: readonly ComponentTargetKind[]
  portability: ComponentPortability
  /** Definition metadata is authoring/runtime policy and is never serialized
   * into a component record. */
  phase: ComponentLifecyclePhase
  cardinality: ComponentCardinality
  requires: readonly ComponentRuntimeCapability[]
  conflicts: readonly string[]
  cost: ComponentRuntimeCost
  adapters: Readonly<ComponentAdapterSupport>
  fallbacks: Readonly<Partial<Record<ComponentAdapterKind, string>>>
  searchSynonyms: readonly string[]
  consequence: string
  fields: Readonly<Record<string, ComponentFieldMetadata>>
}

export interface ComponentDiagnostic {
  severity: 'error' | 'warning'
  path: string
  message: string
}

export interface ParsePortableComponentsResult {
  components: PortableComponentRecord[]
  diagnostics: ComponentDiagnostic[]
}

const objectReference: ComponentFieldMetadata = {
  label: 'Object', description: 'Rename-stable Blendlink object ID.', kind: 'object-reference', default: '',
}

/** First-party records are deliberately small, but the registry is public and
 * vendor namespaces can be retained before a website installs their adapter. */
export const CORE_COMPONENT_REGISTRY: Readonly<Record<string, PortableComponentDefinition>> = {
  'blendlink.bloom': {
    id: 'blendlink.bloom', label: 'Bloom', description: 'Adds a glow pass to the website render.',
    category: 'Presentation', targets: ['scene'], portability: 'adapter',
    phase: 'post-hdr', cardinality: 'one-per-scene',
    requires: ['post-pipeline', 'hdr-color'], conflicts: [], cost: 'medium',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Use the WebGL adapter or disable Bloom explicitly.' },
    searchSynonyms: ['glow', 'halo', 'emission', 'neon', 'bright', 'post processing'],
    consequence: 'Adds an HDR full-screen mip-chain render stage; Blendlink owns the website render path while enabled.',
    fields: {
      mode: {
        label: 'What Blooms',
        description: 'Bloom every pixel above the threshold, or only exported objects whose materials emit light.',
        kind: 'enum', default: 'bright-pixels', options: ['bright-pixels', 'emissive-objects'],
      },
      intensity: { label: 'Intensity', description: 'Bloom brightness.', kind: 'number', default: 0.5, min: 0, max: 100 },
      threshold: {
        label: 'Threshold',
        description: 'Linear scene brightness required to bloom; values below 1 also work on the LDR fallback.',
        kind: 'number', default: 0.8, min: 0, max: 100,
      },
      radius: { label: 'Radius', description: 'How far glow spreads.', kind: 'number', default: 0.4, min: 0, max: 1 },
    },
  },
  'blendlink.vignette': {
    id: 'blendlink.vignette', label: 'Vignette', description: 'Darkens or tints image edges.',
    category: 'Presentation', targets: ['scene'], portability: 'adapter',
    phase: 'post-ldr', cardinality: 'one-per-scene',
    requires: ['post-pipeline'], conflicts: [], cost: 'low',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Use the WebGL adapter or reproduce the treatment in the website design.' },
    searchSynonyms: ['edges', 'frame', 'cinematic', 'focus', 'darken', 'post processing'],
    consequence: 'Adds one full-screen color pass; Blendlink owns the website render path while enabled.',
    fields: {
      intensity: { label: 'Intensity', description: 'Edge treatment strength.', kind: 'number', default: 0.25, min: 0, max: 1 },
      softness: { label: 'Softness', description: 'Width of the vignette transition.', kind: 'number', default: 0.55, min: 0, max: 1 },
      color: { label: 'Color', description: 'Linear RGB vignette color.', kind: 'color', default: [0, 0, 0] },
    },
  },
  'blendlink.chromatic-aberration': {
    id: 'blendlink.chromatic-aberration', label: 'Chromatic Aberration',
    description: 'Adds restrained lens-like color separation to the website image.',
    category: 'Presentation', targets: ['scene'], portability: 'adapter',
    phase: 'post-ldr', cardinality: 'one-per-scene',
    requires: ['post-pipeline'], conflicts: [], cost: 'low',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Use the WebGL chromatic-aberration adapter or disable the effect explicitly.' },
    searchSynonyms: ['rgb split', 'color fringe', 'lens', 'dispersion', 'glitch', 'post processing'],
    consequence: 'Adds one bounded full-screen color pass; strong values can reduce text and silhouette readability.',
    fields: {
      amount: {
        label: 'Amount',
        description: 'Maximum RGB separation in normalized image units; 0.001 is about one pixel across a 1000-pixel image.',
        kind: 'number', default: 0.0015, min: 0, max: 0.05,
      },
      mode: {
        label: 'Pattern',
        description: 'Split colors in one chosen direction or outward from a lens center.',
        kind: 'enum', default: 'radial', options: ['directional', 'radial'],
      },
      angle: {
        label: 'Direction',
        description: 'Directional split angle in degrees; used only when Pattern is Directional.',
        kind: 'number', default: 0, min: -180, max: 180,
      },
      centerX: {
        label: 'Center X',
        description: 'Horizontal lens center from left (0) to right (1); used only when Pattern is Radial.',
        kind: 'number', default: 0.5, min: 0, max: 1,
      },
      centerY: {
        label: 'Center Y',
        description: 'Vertical lens center from bottom (0) to top (1); used only when Pattern is Radial.',
        kind: 'number', default: 0.5, min: 0, max: 1,
      },
    },
  },
  'blendlink.pixelation': {
    id: 'blendlink.pixelation', label: 'Pixelation',
    description: 'Creates a stable block-pixel look with optional geometry-aware edges.',
    category: 'Presentation', targets: ['scene'], portability: 'adapter',
    phase: 'post-ldr', cardinality: 'one-per-scene',
    requires: ['post-pipeline', 'depth', 'normals'], conflicts: [], cost: 'medium',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Use the WebGL pixelation adapter or disable the effect explicitly.' },
    searchSynonyms: ['pixel art', 'retro', 'low resolution', 'blocks', '8 bit', 'geometry edges'],
    consequence: 'Adds one full-screen stage; the CSS-pixel block size stays visually stable across device pixel ratios.',
    fields: {
      pixelSize: {
        label: 'Pixel Size',
        description: 'Block size in CSS pixels, kept visually stable when browser DPR changes.',
        kind: 'number', default: 6, min: 1, max: 256,
      },
      depthEdgeStrength: {
        label: 'Depth Edges',
        description: 'Emphasize boundaries between surfaces at different camera depths; zero disables the extra treatment.',
        kind: 'number', default: 0, min: 0, max: 1,
      },
      normalEdgeStrength: {
        label: 'Normal Edges',
        description: 'Emphasize changes in surface direction; zero disables the extra treatment.',
        kind: 'number', default: 0, min: 0, max: 1,
      },
    },
  },
  'blendlink.sharpen': {
    id: 'blendlink.sharpen', label: 'Contrast-Adaptive Sharpen',
    description: 'Restores local clarity with a bounded FidelityFX-CAS-style pass.',
    category: 'Presentation', targets: ['scene'], portability: 'adapter',
    phase: 'post-ldr', cardinality: 'one-per-scene',
    requires: ['post-pipeline'], conflicts: [], cost: 'low',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Use the WebGL contrast-adaptive sharpen adapter or disable it explicitly.' },
    searchSynonyms: ['cas', 'clarity', 'crisp', 'detail', 'fidelityfx', 'upsampling'],
    consequence: 'Adds one fixed-footprint full-screen pass; shader work cannot grow quadratically with the slider.',
    fields: {
      amount: {
        label: 'Amount',
        description: 'Contrast-adaptive sharpening strength; use modest values to avoid halos and amplified texture noise.',
        kind: 'number', default: 0.35, min: 0, max: 1,
      },
    },
  },
  'blendlink.tilt-shift': {
    id: 'blendlink.tilt-shift', label: 'Tilt Shift',
    description: 'Keeps a controllable band sharp while smoothly blurring either side.',
    category: 'Presentation', targets: ['scene'], portability: 'adapter',
    phase: 'post-hdr', cardinality: 'one-per-scene',
    requires: ['post-pipeline'], conflicts: [], cost: 'high',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Use the WebGL tilt-shift adapter or disable the effect explicitly.' },
    searchSynonyms: ['miniature', 'focus band', 'lens blur', 'photographic', 'selective focus'],
    consequence: 'Adds a separable blur before tone mapping; Quality changes only its internal resolution and kernel policy.',
    fields: {
      focusPosition: {
        label: 'Focus Position',
        description: 'Center of the sharp band across the frame, from 0 to 1.',
        kind: 'number', default: 0.5, min: 0, max: 1,
      },
      angle: {
        label: 'Angle',
        description: 'Rotation of the sharp band in degrees.',
        kind: 'number', default: 0, min: -180, max: 180,
      },
      feather: {
        label: 'Feather',
        description: 'Width of the smooth transition from sharp to blurred image.',
        kind: 'number', default: 0.25, min: 0.001, max: 1,
      },
      strength: {
        label: 'Strength',
        description: 'Maximum blur away from the focus band.',
        kind: 'number', default: 0.7, min: 0, max: 1,
      },
      quality: {
        label: 'Quality',
        description: 'Internal blur resolution and kernel policy; it never changes the authored blur strength.',
        kind: 'enum', default: 'balanced', options: ['low', 'balanced', 'high'],
      },
    },
  },
  'blendlink.ambient-occlusion': {
    id: 'blendlink.ambient-occlusion', label: 'Ambient Occlusion',
    description: 'Adds contact and crevice shading from the website camera.',
    category: 'Rendering', targets: ['scene'], portability: 'adapter',
    phase: 'post-depth', cardinality: 'one-per-scene',
    requires: ['post-pipeline', 'depth', 'normals', 'camera'], conflicts: [], cost: 'high',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Use the WebGL N8AO adapter or disable Ambient Occlusion explicitly.' },
    searchSynonyms: ['ao', 'contact shadow', 'grounding', 'creases', 'depth', 'n8ao'],
    consequence: 'Adds a depth- and normal-aware render stage; transparent geometry can require an additional draw.',
    fields: {
      radiusMode: {
        label: 'Radius Units',
        description: 'Use Blender world units for physical scale or pixels for cameras that cross very different scales.',
        kind: 'enum', default: 'world', options: ['world', 'screen'],
      },
      worldRadius: {
        label: 'World Radius', description: 'How far occlusion reaches in Blender world units.',
        kind: 'number', default: 1, min: 0.000001, max: 100000,
      },
      screenRadius: {
        label: 'Screen Radius', description: 'How far occlusion reaches in rendered pixels when Radius Units is Screen.',
        kind: 'number', default: 32, min: 1, max: 256,
      },
      intensity: {
        label: 'Strength', description: 'Artistic darkness of the occlusion.',
        kind: 'number', default: 2, min: 0, max: 20,
      },
      color: { label: 'Tint', description: 'Linear RGB occlusion tint.', kind: 'color', default: [0, 0, 0] },
    },
  },
  'blendlink.shadow-catcher': {
    id: 'blendlink.shadow-catcher', label: 'Shadow Catcher',
    description: 'Receives authored realtime shadows or acts as an invisible depth occluder.',
    category: 'Rendering', targets: ['object'], portability: 'adapter',
    phase: 'initial', cardinality: 'one-per-target',
    requires: [], conflicts: [], cost: 'low',
    adapters: { webgl: 'preview', tsl: 'fallback' },
    fallbacks: {
      tsl: 'Mask and Occluder use standard Three materials; Additive requires the supported WebGL lighting seam.',
    },
    searchSynonyms: ['shadow plane', 'ground shadow', 'mask', 'occluder', 'compositing'],
    consequence: 'Replaces materials on every mesh beneath the target while installed, then restores authored materials transactionally.',
    fields: {
      mode: {
        label: 'Mode',
        description: 'Render only received shadows, add direct light over the page, or write invisible depth.',
        kind: 'enum', default: 'mask', options: ['mask', 'additive', 'occluder'],
      },
      color: {
        label: 'Shadow Tint',
        description: 'Linear RGB tint used only by Shadow Mask mode.',
        kind: 'color', default: [0, 0, 0],
      },
      opacity: {
        label: 'Shadow Opacity',
        description: 'Mask strength used only by Shadow Mask mode.',
        kind: 'number', default: 0.5, min: 0, max: 1,
      },
      lightStrength: {
        label: 'Additive Light Strength',
        description: 'Direct-light multiplier used only in Additive mode.',
        kind: 'number', default: 6.6, min: 0, max: 20,
      },
      includeDescendants: {
        label: 'Include Child Meshes',
        description: 'Apply to renderable children as one authored receiver; turn off to use only this mesh or an automatic plane.',
        kind: 'boolean', default: true,
      },
    },
  },
  'blendlink.contact-shadows': {
    id: 'blendlink.contact-shadows', label: 'Contact Shadows',
    description: 'Grounds objects with a soft depth-derived shadow on an authored or automatic plane.',
    category: 'Rendering', targets: ['scene', 'object'], portability: 'adapter',
    phase: 'update', cardinality: 'one-per-scene',
    requires: [], conflicts: [], cost: 'high',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: {
      tsl: 'Use the matched WebGL adapter; the Three.js TSL example has a different kernel and is not yet parity-verified.',
    },
    searchSynonyms: ['ground shadow', 'soft shadow', 'product shadow', 'contact', 'grounding'],
    consequence: 'Refreshes one depth mask plus four blur passes; Static settles after the first valid frame while Continuous repeats all five passes.',
    fields: {
      autoFit: {
        label: 'Fit to Scene',
        description: 'Automatically size and place the receiver from the complete compiled scene.',
        kind: 'boolean', default: true,
      },
      darkness: {
        label: 'Darkness',
        description: 'Depth-mask strength before the blurred shadow is composited.',
        kind: 'number', default: 0.5, min: 0, max: 20,
      },
      opacity: {
        label: 'Opacity',
        description: 'Final opacity of the contact-shadow receiver.',
        kind: 'number', default: 0.5, min: 0, max: 1,
      },
      blur: {
        label: 'Blur',
        description: 'Softness of the shadow edge using Needle-compatible two-scale Gaussian blur.',
        kind: 'number', default: 4, min: 0, max: 100,
      },
      occludeBelowGround: {
        label: 'Hide Below Ground',
        description: 'Write invisible ground depth so geometry below the receiver does not show through.',
        kind: 'boolean', default: false,
      },
      backfaceShadows: {
        label: 'Backface Shadows',
        description: 'Let backfaces contribute at reduced strength, matching the Needle component.',
        kind: 'boolean', default: true,
      },
      updatePolicy: {
        label: 'Update',
        description: 'Static renders once and settles; Continuous refreshes for animated or moving geometry.',
        kind: 'enum', default: 'static', options: ['static', 'continuous'],
      },
    },
  },
  'blendlink.outline': {
    id: 'blendlink.outline', label: 'Outline',
    description: 'Draws a readable silhouette around the rendered scene.',
    category: 'Rendering', targets: ['scene'], portability: 'adapter',
    phase: 'post-ldr', cardinality: 'one-per-scene',
    requires: ['post-pipeline', 'depth', 'camera'], conflicts: [], cost: 'medium',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Use the WebGL outline adapter or disable Outline explicitly.' },
    searchSynonyms: ['edge', 'silhouette', 'stroke', 'toon', 'cel shading', 'xray'],
    consequence: 'Adds a depth-aware edge stage over every rendered mesh; X-Ray also reveals hidden silhouettes.',
    fields: {
      visibleColor: { label: 'Visible Color', description: 'Linear RGB color for visible silhouettes.', kind: 'color', default: [0, 0, 0] },
      hiddenColor: { label: 'Hidden Color', description: 'Linear RGB color for occluded silhouettes when X-Ray is enabled.', kind: 'color', default: [0.08, 0.08, 0.08] },
      strength: { label: 'Strength', description: 'Contrast of the outline.', kind: 'number', default: 3, min: 0, max: 100 },
      thickness: { label: 'Thickness', description: 'Approximate outline width in rendered pixels.', kind: 'number', default: 1, min: 0, max: 16 },
      xRay: { label: 'X-Ray', description: 'Also draw silhouettes hidden behind other geometry.', kind: 'boolean', default: false },
    },
  },
  'blendlink.color-grading': {
    id: 'blendlink.color-grading', label: 'Color Grade',
    description: 'Applies an authored 3D lookup table to the final website image.',
    category: 'Presentation', targets: ['scene'], portability: 'adapter',
    phase: 'post-ldr', cardinality: 'one-per-scene',
    requires: ['post-pipeline'], conflicts: [], cost: 'medium',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Use the WebGL LUT adapter or reproduce the grade in the host site.' },
    searchSynonyms: ['lut', 'look', 'grade', 'film', 'color correction', 'cube'],
    consequence: 'Loads one published LUT asset and adds a full-frame color lookup after tone mapping.',
    fields: {
      lutUrl: {
        label: 'LUT URL', description: 'Site-relative or HTTPS URL of a published .cube or supported 3D LUT asset.',
        kind: 'string', default: '', required: true,
      },
      intensity: { label: 'Intensity', description: 'Blend between the ungraded image and the LUT.', kind: 'number', default: 1, min: 0, max: 1 },
      tetrahedralInterpolation: {
        label: 'Tetrahedral Interpolation',
        description: 'Use the more accurate interpolation path for 3D LUTs at a modest GPU cost.',
        kind: 'boolean', default: true,
      },
    },
  },
  'blendlink.depth-of-field': {
    id: 'blendlink.depth-of-field', label: 'Depth of Field',
    description: 'Keeps a chosen distance or scene object sharp while softening foreground and background.',
    category: 'Presentation', targets: ['scene'], portability: 'adapter',
    phase: 'post-depth', cardinality: 'one-per-scene',
    requires: ['post-pipeline', 'depth', 'camera'], conflicts: [], cost: 'high',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Use the WebGL depth-of-field adapter or disable the effect explicitly.' },
    searchSynonyms: ['dof', 'focus', 'bokeh', 'lens', 'camera blur', 'cinematic'],
    consequence: 'Adds depth sampling and multi-resolution blur; transparent surfaces may not focus like opaque geometry.',
    fields: {
      focusMode: {
        label: 'Focus With', description: 'Use a fixed camera distance or follow a rename-stable scene object.',
        kind: 'enum', default: 'distance', options: ['distance', 'object'],
      },
      focusDistance: { label: 'Focus Distance', description: 'Sharp distance from the camera in Blender world units.', kind: 'number', default: 3, min: 0.000001, max: 1000000 },
      focusRange: { label: 'Focus Range', description: 'Depth around the focus plane that remains sharp.', kind: 'number', default: 2, min: 0.000001, max: 1000000 },
      blurStrength: { label: 'Blur Strength', description: 'Maximum foreground and background blur.', kind: 'number', default: 1, min: 0, max: 20 },
      focusTargetId: { ...objectReference, label: 'Focus Object' },
      focusTargetName: { label: 'Focus Object Name', description: 'Artist-facing focus-object diagnostic.', kind: 'string', default: '' },
    },
  },
  'blendlink.kuwahara': {
    id: 'blendlink.kuwahara', label: 'Kuwahara Painterly Filter',
    description: 'Applies a bounded single-pass directional painterly approximation while retaining strong edges.',
    category: 'Presentation', targets: ['scene'], portability: 'adapter',
    phase: 'post-ldr', cardinality: 'one-per-scene',
    requires: ['post-pipeline'], conflicts: [], cost: 'very-high',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: {
      webgl: 'Experimental Preview approximation: validate appearance, motion, and performance on target devices before publishing.',
      tsl: 'Use the WebGL preview adapter or disable Kuwahara explicitly.',
    },
    searchSynonyms: ['paint', 'painterly', 'stylized', 'brush', 'anime', 'oil paint', 'anisotropic'],
    consequence: 'Adds one full-resolution high-sample shader; runtime quality changes sample count and filter radius, so appearance may change.',
    fields: {
      strength: { label: 'Strength', description: 'Blend between the original image and the painterly result.', kind: 'number', default: 0.75, min: 0, max: 1 },
      brushScale: { label: 'Brush Scale', description: 'Size of the coherent painted regions in rendered pixels.', kind: 'number', default: 4, min: 1, max: 32 },
      directionality: { label: 'Directionality', description: 'How strongly local image structure guides brush direction.', kind: 'number', default: 0.75, min: 0, max: 1 },
      detail: { label: 'Detail', description: 'Retains smaller features while simplifying low-contrast regions.', kind: 'number', default: 0.5, min: 0, max: 1 },
    },
  },
  'blendlink.see-through': {
    id: 'blendlink.see-through', label: 'Keep Visible Through Objects', description: 'Fades intervening meshes so the focal object remains visible.',
    category: 'Rendering', targets: ['object'], portability: 'adapter',
    phase: 'update', cardinality: 'one-per-target',
    requires: ['camera', 'raycast'], conflicts: [], cost: 'low',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Provide a renderer-specific raycast and material adapter.' },
    searchSynonyms: ['xray', 'occlusion', 'fade', 'transparent', 'hero', 'always visible'],
    consequence: 'Clones and temporarily fades occluding materials; authored materials are restored on disposal.',
    fields: {
      fadeDistance: { label: 'Subject Clearance', description: 'Keep objects this close to the focal object fully visible.', kind: 'number', default: 0.5, min: 0, max: 100000 },
      minOpacity: { label: 'Minimum Opacity', description: 'Lowest opacity used for intervening objects.', kind: 'number', default: 0.15, min: 0, max: 1 },
      duration: { label: 'Fade Time', description: 'Seconds used to fade obstacles in or out.', kind: 'number', default: 0.12, min: 0, max: 60 },
    },
  },
  'blendlink.open-url': {
    id: 'blendlink.open-url', label: 'Open Link', description: 'Opens a URL from an object interaction.',
    category: 'Interaction', targets: ['object'], portability: 'adapter',
    phase: 'initial', cardinality: 'one-per-target',
    requires: ['pointer', 'raycast', 'dom-accessibility'], conflicts: [], cost: 'low',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Provide picking through a site adapter; the URL intent remains portable.' },
    searchSynonyms: ['link', 'click', 'website', 'navigation', 'button', 'tap'],
    consequence: 'Makes the target interactive and delegates navigation to the host browser policy.',
    fields: {
      label: { label: 'Accessible Label', description: 'Human-facing name for an application-owned link or button.', kind: 'string', default: 'Open link' },
      url: { label: 'URL', description: 'Destination URL.', kind: 'string', default: '', required: true },
      newTab: { label: 'Open in New Tab', description: 'Open the link in a separate tab.', kind: 'boolean', default: true },
    },
  },
  'blendlink.hover': {
    id: 'blendlink.hover', label: 'Hover', description: 'Adds a small, accessible hover emphasis.',
    category: 'Interaction', targets: ['object'], portability: 'adapter',
    phase: 'update', cardinality: 'one-per-target',
    requires: ['pointer', 'raycast'], conflicts: [], cost: 'low',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Provide picking through a site adapter; touch devices retain their authored scale.' },
    searchSynonyms: ['rollover', 'pointer', 'highlight', 'scale', 'emphasize', 'button'],
    consequence: 'Temporarily owns the target scale and restores the authored value on disposal.',
    fields: {
      duration: { label: 'Duration', description: 'Seconds for the response.', kind: 'number', default: 0.12, min: 0, max: 60 },
      scale: { label: 'Scale', description: 'Scale factor while hovered.', kind: 'number', default: 1.08, min: 0.01, max: 100 },
    },
  },
  'blendlink.website-surface': {
    id: 'blendlink.website-surface', label: 'Website Surface',
    description: 'Lets the website supply live pixels to a Blender-authored surface.',
    category: 'Interaction', targets: ['object'], portability: 'adapter',
    phase: 'initial', cardinality: 'one-per-target',
    requires: [], conflicts: [], cost: 'low',
    adapters: { webgl: 'production', tsl: 'unavailable' },
    fallbacks: {
      tsl: 'Use the verified WebGL adapter; WebGPU/TSL texture ownership has not been validated yet.',
    },
    searchSynonyms: ['screen', 'monitor', 'canvas', 'live texture', 'application pixels', 'website pixels'],
    consequence: 'Keeps Blender ownership of geometry, UVs, and fallback art while the application supplies pixels through one named, restorable texture lease.',
    fields: {
      name: {
        label: 'Website Name',
        description: 'Stable lowercase name used by application code, for example monitor-screen.',
        kind: 'string', default: 'surface', required: true,
      },
      colorTreatment: {
        label: 'Color Treatment',
        description: 'Display shows pixels unlit; Surface keeps the authored material response.',
        kind: 'enum', default: 'display', options: ['display', 'surface'],
      },
    },
  },
  'blendlink.hide-on-start': {
    id: 'blendlink.hide-on-start', label: 'Hide on Start', description: 'Hides this object when the website scene starts.',
    category: 'Interaction', targets: ['object'], portability: 'core',
    phase: 'initial', cardinality: 'one-per-target',
    requires: [], conflicts: [], cost: 'free',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'The intent is renderer-neutral, but Blendlink does not ship a TSL runtime adapter yet.' },
    searchSynonyms: ['visibility', 'disable', 'initial', 'hidden', 'inactive'],
    consequence: 'Changes only runtime visibility and restores the authored value on disposal.',
    fields: {},
  },
  'blendlink.look-at': {
    id: 'blendlink.look-at', label: 'Look At', description: 'Keeps an object aimed at another object.',
    category: 'Animation', targets: ['object'], portability: 'adapter',
    phase: 'update', cardinality: 'one-per-target',
    requires: ['camera'], conflicts: [], cost: 'low',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'The intent is renderer-neutral, but Blendlink does not ship a TSL runtime adapter yet.' },
    searchSynonyms: ['track', 'constraint', 'billboard', 'face', 'target', 'camera facing'],
    consequence: 'Owns the target rotation every frame while leaving position and scale authored.',
    fields: {
      targetId: { ...objectReference, label: 'Target', required: true },
      targetName: { label: 'Target Name', description: 'Artist-facing target diagnostic.', kind: 'string', default: '' },
      keepUp: { label: 'Keep Up Direction', description: 'Keep the authored up axis.', kind: 'boolean', default: true },
    },
  },
  'blendlink.play-animation-on-click': {
    id: 'blendlink.play-animation-on-click', label: 'Play Animation on Click', description: 'Plays an exported animation clip from an interaction.',
    category: 'Animation', targets: ['object'], portability: 'adapter',
    phase: 'update', cardinality: 'one-per-target',
    requires: ['animation', 'pointer', 'raycast'], conflicts: [], cost: 'low',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Provide picking through a site adapter; exported animation remains standard glTF.' },
    searchSynonyms: ['action', 'clip', 'timeline', 'trigger', 'pointer', 'tap'],
    consequence: 'Creates an animation mixer and owns the chosen action after activation.',
    fields: {
      label: { label: 'Accessible Label', description: 'Human-facing name for an application-owned button.', kind: 'string', default: 'Play animation' },
      clip: { label: 'Clip', description: 'Exact exported glTF clip name.', kind: 'string', default: '', required: true },
      loop: { label: 'Loop', description: 'Repeat the clip when it ends.', kind: 'boolean', default: false },
    },
  },
  'blendlink.audio-source': {
    id: 'blendlink.audio-source', label: 'Audio Source', description: 'Plays an audio file, optionally with predictable spatial falloff.',
    category: 'Audio', targets: ['object'], portability: 'adapter',
    phase: 'initial', cardinality: 'one-per-target',
    requires: ['audio'], conflicts: [], cost: 'low',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Web Audio is portable, but Blendlink does not ship a TSL runtime adapter yet.' },
    searchSynonyms: ['sound', 'music', 'positional', 'speaker', 'media', 'spatial'],
    consequence: 'Loads one audio asset; autoplay may wait for a visitor gesture and spatial sound adds a Web Audio panner.',
    fields: {
      url: { label: 'Audio URL', description: 'Published audio asset URL.', kind: 'string', default: '', required: true },
      autoplay: { label: 'Autoplay', description: 'Start after browser interaction permits audio.', kind: 'boolean', default: false },
      loop: { label: 'Loop', description: 'Repeat playback.', kind: 'boolean', default: false },
      volume: { label: 'Volume', description: 'Linear volume.', kind: 'number', default: 1, min: 0, max: 1 },
      spatial: { label: 'Spatial Audio', description: 'Position the audio in 3D.', kind: 'boolean', default: false },
      minDistance: { label: 'Full Volume Within', description: 'Sound stays at its authored volume inside this radius.', kind: 'number', default: 2, min: 0, max: 100000 },
      maxDistance: { label: 'Silent Beyond', description: 'Sound fades linearly to silence at this radius.', kind: 'number', default: 50, min: 0, max: 100000 },
    },
  },
  'blendlink.play-audio-on-click': {
    id: 'blendlink.play-audio-on-click', label: 'Play Audio on Click', description: 'Starts or toggles an Audio Source from an interaction.',
    category: 'Audio', targets: ['object'], portability: 'adapter',
    phase: 'initial', cardinality: 'one-per-target',
    requires: ['audio', 'pointer', 'raycast'], conflicts: [], cost: 'low',
    adapters: { webgl: 'preview', tsl: 'unavailable' },
    fallbacks: { tsl: 'Provide picking through a site adapter; audio playback remains Web Audio.' },
    searchSynonyms: ['sound', 'trigger', 'pointer', 'button', 'toggle', 'tap'],
    consequence: 'Reuses the referenced Audio Source and adds an activation target without duplicating media.',
    fields: {
      label: { label: 'Accessible Label', description: 'Human-facing name for an application-owned button.', kind: 'string', default: 'Play audio' },
      sourceId: { ...objectReference, label: 'Audio Source', required: true },
      sourceName: { label: 'Source Name', description: 'Artist-facing source diagnostic.', kind: 'string', default: '' },
      toggle: { label: 'Toggle', description: 'Toggle playback instead of always starting it.', kind: 'boolean', default: false },
    },
  },
}

export function componentDefinition(type: string): PortableComponentDefinition | undefined {
  return CORE_COMPONENT_REGISTRY[type]
}

export function componentDefaults(type: string): JsonObject | undefined {
  const definition = componentDefinition(type)
  if (!definition) return undefined
  const values: Record<string, JsonValue> = {}
  for (const [name, field] of Object.entries(definition.fields)) values[name] = field.default
  return values
}

/** Parse without erasing a vendor component. Errors reject malformed records;
 * a well-formed unknown namespace becomes a warning and remains available to
 * its future website adapter. */
export function parsePortableComponents(value: unknown): ParsePortableComponentsResult {
  const diagnostics: ComponentDiagnostic[] = []
  if (value === undefined) return { components: [], diagnostics }
  if (!Array.isArray(value)) {
    return { components: [], diagnostics: [{ severity: 'error', path: 'components', message: 'components must be a list' }] }
  }
  const components: PortableComponentRecord[] = []
  const ids = new Set<string>()
  const placements = new Set<string>()
  const websiteSurfaceNames = new Set<string>()
  for (const [index, raw] of value.entries()) {
    const path = `components[${index}]`
    if (!isRecord(raw)) {
      diagnostics.push({ severity: 'error', path, message: 'component must be an object' })
      continue
    }
    const id = stringValue(raw.id)
    const type = stringValue(raw.type)
    const schemaVersion = raw.schemaVersion
    const enabled = raw.enabled
    const target = parseTarget(raw.target, `${path}.target`, diagnostics)
    const values = raw.values
    let valid = true
    if (!isStableId(id)) {
      diagnostics.push({ severity: 'error', path: `${path}.id`, message: 'component id must be a non-empty stable identifier' })
      valid = false
    } else if (ids.has(id)) {
      diagnostics.push({ severity: 'error', path: `${path}.id`, message: `duplicate component id "${id}"` })
      valid = false
    }
    ids.add(id)
    if (!isComponentType(type)) {
      diagnostics.push({ severity: 'error', path: `${path}.type`, message: 'component type must be a vendor-namespaced identifier' })
      valid = false
    }
    if (schemaVersion !== PORTABLE_COMPONENT_SCHEMA_VERSION) {
      diagnostics.push({ severity: 'error', path: `${path}.schemaVersion`, message: `component schemaVersion must be ${PORTABLE_COMPONENT_SCHEMA_VERSION}` })
      valid = false
    }
    if (typeof enabled !== 'boolean') {
      diagnostics.push({ severity: 'error', path: `${path}.enabled`, message: 'component enabled must be boolean' })
      valid = false
    }
    if (!isJsonObject(values)) {
      diagnostics.push({ severity: 'error', path: `${path}.values`, message: 'component values must be a JSON object' })
      valid = false
    }
    if (!target) valid = false
    if (!valid || !target || !isJsonObject(values) || typeof enabled !== 'boolean') continue
    const component: PortableComponentRecord = {
      id, type, schemaVersion: PORTABLE_COMPONENT_SCHEMA_VERSION, enabled, target, values,
    }
    const definition = componentDefinition(type)
    const placement = definition?.cardinality === 'one-per-scene'
      ? `${type}\u0000scene`
      : `${type}\u0000${target.kind === 'scene' ? 'scene' : target.objectId}`
    if (placements.has(placement)) {
      diagnostics.push({
        severity: 'error', path,
        message: definition?.cardinality === 'one-per-scene'
          ? `component "${type}" is already assigned in this scene`
          : `component "${type}" is already assigned to this target`,
      })
    }
    placements.add(placement)
    if (!definition) {
      diagnostics.push({ severity: 'warning', path: `${path}.type`, message: `component "${type}" requires a website adapter; preserved unchanged` })
    } else {
      validateCoreComponent(component, definition, path, diagnostics)
    }
    if (component.type === 'blendlink.website-surface') {
      const name = component.values.name
      if (typeof name === 'string' && /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(name) && name.length <= 64) {
        if (websiteSurfaceNames.has(name)) {
          diagnostics.push({
            severity: 'error', path: `${path}.values.name`,
            message: `Website Surface name "${name}" is already used in this scene`,
          })
        }
        websiteSurfaceNames.add(name)
      }
    }
    components.push(component)
  }
  return { components, diagnostics }
}

function validateCoreComponent(
  component: PortableComponentRecord,
  definition: PortableComponentDefinition,
  path: string,
  diagnostics: ComponentDiagnostic[],
): void {
  if (!definition.targets.includes(component.target.kind)) {
    diagnostics.push({ severity: 'error', path: `${path}.target`, message: `${definition.label} targets ${definition.targets.join(' or ')}` })
  }
  for (const [name, value] of Object.entries(component.values)) {
    const field = definition.fields[name]
    if (!field) {
      diagnostics.push({ severity: 'warning', path: `${path}.values.${name}`, message: `unknown ${definition.label} field preserved for a newer adapter` })
      continue
    }
    validateField(value, field, `${path}.values.${name}`, diagnostics)
  }
  for (const [name, field] of Object.entries(definition.fields)) {
    if (component.enabled && field.required && (component.values[name] === undefined || (typeof component.values[name] === 'string' && !component.values[name].trim()))) {
      diagnostics.push({ severity: 'error', path: `${path}.values.${name}`, message: `${field.label} is required` })
    }
    if (field.kind === 'object-reference' && component.values[name] !== undefined && component.values[name] !== '' && !isStableId(component.values[name])) {
      diagnostics.push({ severity: 'error', path: `${path}.values.${name}`, message: `${field.label} must be a stable object ID` })
    }
  }
  if (component.type === 'blendlink.open-url') {
    validateComponentUrl(component.values.url, new Set(['http', 'https', 'mailto', 'tel']), `${path}.values.url`, diagnostics)
  } else if (component.type === 'blendlink.audio-source') {
    validateComponentUrl(component.values.url, new Set(['http', 'https']), `${path}.values.url`, diagnostics)
    const minimum = component.values.minDistance
    const maximum = component.values.maxDistance
    if (typeof minimum === 'number' && typeof maximum === 'number' && maximum <= minimum) {
      diagnostics.push({
        severity: 'error', path: `${path}.values.maxDistance`,
        message: 'Silent Beyond must be farther than Full Volume Within',
      })
    }
  } else if (component.type === 'blendlink.color-grading') {
    validateComponentUrl(component.values.lutUrl, new Set(['http', 'https']), `${path}.values.lutUrl`, diagnostics)
  } else if (component.type === 'blendlink.depth-of-field' && component.enabled && component.values.focusMode === 'object') {
    if (!isStableId(component.values.focusTargetId)) {
      diagnostics.push({
        severity: 'error', path: `${path}.values.focusTargetId`,
        message: 'Focus Object is required when Focus With is object',
      })
    }
  } else if (component.type === 'blendlink.chromatic-aberration' && component.enabled) {
    const amount = component.values.amount
    if (typeof amount === 'number' && amount > 0.01) {
      diagnostics.push({
        severity: 'warning', path: `${path}.values.amount`,
        message: 'Strong chromatic aberration can reduce readability; values at or below 0.01 are safer for most scenes',
      })
    }
  } else if (component.type === 'blendlink.pixelation') {
    const pixelSize = component.values.pixelSize
    if (typeof pixelSize === 'number' && Number.isFinite(pixelSize) && !Number.isInteger(pixelSize)) {
      diagnostics.push({
        severity: 'error', path: `${path}.values.pixelSize`,
        message: 'Pixel Size must be a whole number of CSS pixels',
      })
    }
  } else if (component.type === 'blendlink.website-surface') {
    const name = component.values.name
    if (typeof name === 'string' && (!/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(name) || name.length > 64)) {
      diagnostics.push({
        severity: 'error', path: `${path}.values.name`,
        message: 'Website Name must be lowercase kebab-case, up to 64 characters (for example monitor-screen)',
      })
    }
  }
}

function validateComponentUrl(
  value: JsonValue | undefined,
  allowedSchemes: ReadonlySet<string>,
  path: string,
  diagnostics: ComponentDiagnostic[],
): void {
  if (typeof value !== 'string' || !value.trim()) return
  const scheme = /^([a-z][a-z0-9+.-]*):/i.exec(value.trim())?.[1]?.toLowerCase()
  if (scheme && !allowedSchemes.has(scheme)) {
    diagnostics.push({
      severity: 'error', path,
      message: `URL scheme ${scheme}: is unsupported; use ${[...allowedSchemes].join(', ')} or a site-relative path`,
    })
  }
}

function validateField(value: JsonValue, field: ComponentFieldMetadata, path: string, diagnostics: ComponentDiagnostic[]): void {
  if (field.kind === 'boolean' && typeof value !== 'boolean') {
    diagnostics.push({ severity: 'error', path, message: `${field.label} must be boolean` })
  } else if (field.kind === 'number') {
    if (typeof value !== 'number' || !Number.isFinite(value)) diagnostics.push({ severity: 'error', path, message: `${field.label} must be a finite number` })
    else if ((field.min !== undefined && value < field.min) || (field.max !== undefined && value > field.max)) diagnostics.push({ severity: 'error', path, message: `${field.label} is outside its supported range` })
  } else if ((field.kind === 'string' || field.kind === 'object-reference') && typeof value !== 'string') {
    diagnostics.push({ severity: 'error', path, message: `${field.label} must be text` })
  } else if (field.kind === 'enum' && (typeof value !== 'string' || !field.options?.includes(value))) {
    diagnostics.push({ severity: 'error', path, message: `${field.label} must be one of ${field.options?.join(', ')}` })
  } else if (field.kind === 'color' && (!Array.isArray(value) || value.length !== 3 || value.some((entry) => typeof entry !== 'number' || !Number.isFinite(entry)))) {
    diagnostics.push({ severity: 'error', path, message: `${field.label} must be an RGB number tuple` })
  }
}

function parseTarget(value: unknown, path: string, diagnostics: ComponentDiagnostic[]): PortableComponentTarget | null {
  if (!isRecord(value)) {
    diagnostics.push({ severity: 'error', path, message: 'component target must be an object' })
    return null
  }
  if (value.kind === 'scene') return SCENE_COMPONENT_TARGET
  if (value.kind === 'object') {
    const objectId = stringValue(value.objectId)
    if (!isStableId(objectId)) {
      diagnostics.push({ severity: 'error', path: `${path}.objectId`, message: 'object target needs a stable object ID' })
      return null
    }
    const objectName = typeof value.objectName === 'string' && value.objectName.trim()
      ? value.objectName.trim()
      : undefined
    return { kind: 'object', objectId, ...(objectName ? { objectName } : {}) }
  }
  diagnostics.push({ severity: 'error', path: `${path}.kind`, message: 'target kind must be scene or object' })
  return null
}

function isComponentType(value: string): boolean {
  return /^[a-z][a-z0-9-]*(?:\.[a-z][a-z0-9-]*)+$/.test(value)
}

function isStableId(value: unknown): value is string {
  return typeof value === 'string' && value.trim().length > 0 && value.length <= 256
}

function stringValue(value: unknown): string {
  return typeof value === 'string' ? value.trim() : ''
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === 'object' && !Array.isArray(value)
}

function isJsonObject(value: unknown): value is JsonObject {
  return isJsonValue(value, new WeakSet<object>()) && isRecord(value)
}

/** Reject functions, undefined, non-finite numbers, class instances, and
 * cycles before an export reaches JSON.stringify. */
export function isJsonValue(value: unknown, ancestors = new WeakSet<object>()): value is JsonValue {
  if (value === null || typeof value === 'string' || typeof value === 'boolean') return true
  if (typeof value === 'number') return Number.isFinite(value)
  if (!value || typeof value !== 'object') return false
  if (ancestors.has(value)) return false
  const prototype = Object.getPrototypeOf(value)
  if (prototype !== Object.prototype && prototype !== null && !Array.isArray(value)) return false
  ancestors.add(value)
  const valid = Array.isArray(value)
    ? value.every((entry) => isJsonValue(entry, ancestors))
    : Object.values(value).every((entry) => isJsonValue(entry, ancestors))
  ancestors.delete(value)
  return valid
}
