export { defineConfig, defineScene, loadConfig, resolveConfig } from './config.js'
export type { BlendlinkConfig, SceneConfig, ResolvedConfig, ResolvedScene } from './config.js'
export { discoverBlender, BlenderNotFoundError } from './discover.js'
export type { BlenderInstall } from './discover.js'
export { exportBlend, BlendExportError } from './invoke.js'
export type { ExportSettings, ExportResult } from './invoke.js'
export { readBlendHeader } from './blendHeader.js'
export type { BlendHeader } from './blendHeader.js'
export { generateSceneModule } from './typegen.js'
export type { SceneManifest, NodeKind, TypegenOutput } from './typegen.js'
export { syncAll, syncScene, verifyAll } from './sync.js'
export type { SyncOutcome, VerifyIssue } from './sync.js'
